### ISSUE TITLE
[feature request] add an option to get single window for documentation

### ISSUE THREAD

**Issue by Fat-Zer** [powerman/vim-plugin-viewdoc#46]
Good day, I wish there were an option to hava a single window designated for docs opened in a splitwindow. I.e. like current mode with g:viewdoc_open="belowright vnew" but on entering a yet another :ViewDoc* command the content of the already opened page would be replaced by the requested doc.

I thought
```
g:viewdoc_open="belowright vnew"
g:viewdoc_only=1
```
will get this result, but it works as in single window mode.

**Comment by powerman** [comment]
`g:viewdoc_only=1` have effect of `:only` Vim command applied to doc window, so it's unlikely what you want in multi-window workflow.

If I understand what you want, then you need effect of `K` key instead of `F1` key - `K` open doc for word under cursor in same single doc window, while `F1` open each next doc in new window. (BTW, `K` doesn't reuse windows already opened by `F1`, it reuse only window opened by previous `K`.) To have same effect as `K` using command line you should append `!` to `ViewDoc` command: `:ViewDoc! <some-topic>`.

Is that helps?

**Comment by Fat-Zer** [comment]
yes, thanks... figured out that myself about half an hour ago... sorry for bothering...
