### ISSUE TITLE
use as manpager

### ISSUE THREAD

**Issue by slipsnip** [powerman/vim-plugin-viewdoc#53]
In your readme you list that I can use this for my manpager but I have been unable to locate instructions on how to do so using :ViewDocHelp viewdoc

I have done the following export
export MANPAGER="/bin/sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
which when I enter man <command> into my terminal does launch nvim into man page, it does not appear to be using viewdoc to read the man file.  Do you have any suggestions on how to do so?  Is it already mentioned in the help documentation?

Been using this plugin for about two weeks and love it.

**Comment by powerman** [comment]
Yeah, sorry, looks like this wasn't documented. I'm using custom script `~/bin/man` to make it work in any shell (some time ago it was a bash alias AFAIR, but since I start using both bash and zsh it became more convenient to move it to separate script). Here is my setup:
```sh
$ echo $PAGER
/usr/bin/less
$ cat ~/bin/man
#!/bin/bash

# try to detect when called from bash's autocomplete
if [ "$PAGER" == "/bin/cat" ]; then
	exec env LANG=en_US.UTF-8 /usr/bin/man $*
fi

if [ ${1:0:1} == "-" ]; then
	exec env LANG=en_US.UTF-8 /usr/bin/man $*
else
	exec vi --cmd 'let g:loaded_autosess=1' -c "ViewDocMan $*" -c tabonly
fi
$
```
(The `g:loaded_autosess` thing is for another one my plugin: https://github.com/powerman/vim-plugin-autosess.)
